[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = ["cd web && pip install -r requirements.txt"]

[build.nixpacksPlan.start]
cmd = "cd web && python app.py"
